import type { ComponentType, CSSProperties } from "react";
import {
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiTypescript,
  SiTailwindcss,
  SiGreensock,
  SiFramer,
  SiNodedotjs,
  SiExpress,
  SiFastapi,
  SiPython,
  SiGo,
  SiRuby,
  SiRust,
  SiZod,
  SiJsonwebtokens,
  SiPostgresql,
  SiMongodb,
  SiRedis,
  SiPrisma,
  SiDocker,
  SiKubernetes,
  SiJaeger,
  SiFigma,
} from "react-icons/si";
import { FaAws } from "react-icons/fa6";
import {
  Network,
  ArrowLeftRight,
  Sparkles,
  Component,
  Accessibility,
} from "lucide-react";

type IconComponent = ComponentType<{ className?: string; style?: CSSProperties }>;

/** Brand icon + colour for each tech, keyed by the exact label in `skillGroups`. */
export const techMeta: Record<string, { Icon: IconComponent; color: string }> = {
  React: { Icon: SiReact, color: "#61DAFB" },
  "Next.js": { Icon: SiNextdotjs, color: "#FFFFFF" },
  "Vue.js": { Icon: SiVuedotjs, color: "#4FC08D" },
  TypeScript: { Icon: SiTypescript, color: "#3178C6" },
  "Tailwind CSS": { Icon: SiTailwindcss, color: "#38BDF8" },
  GSAP: { Icon: SiGreensock, color: "#0AE448" },
  "Framer Motion": { Icon: SiFramer, color: "#4F86FF" },
  "Node.js": { Icon: SiNodedotjs, color: "#5FA04E" },
  Express: { Icon: SiExpress, color: "#E6E6E6" },
  FastAPI: { Icon: SiFastapi, color: "#009688" },
  Python: { Icon: SiPython, color: "#4B8BBE" },
  Go: { Icon: SiGo, color: "#00ADD8" },
  Ruby: { Icon: SiRuby, color: "#CC342D" },
  Rust: { Icon: SiRust, color: "#DEA584" },
  REST: { Icon: Network, color: "#9AA0A6" },
  WebSockets: { Icon: ArrowLeftRight, color: "#9AA0A6" },
  JWT: { Icon: SiJsonwebtokens, color: "#FB015B" },
  Zod: { Icon: SiZod, color: "#408AFF" },
  PostgreSQL: { Icon: SiPostgresql, color: "#5189C8" },
  MongoDB: { Icon: SiMongodb, color: "#47A248" },
  Redis: { Icon: SiRedis, color: "#FF4438" },
  Prisma: { Icon: SiPrisma, color: "#E2E8F0" },
  Docker: { Icon: SiDocker, color: "#2496ED" },
  Kubernetes: { Icon: SiKubernetes, color: "#326CE5" },
  Jaeger: { Icon: SiJaeger, color: "#66CFE3" },
  AWS: { Icon: FaAws, color: "#FF9900" },
  Figma: { Icon: SiFigma, color: "#F24E1E" },
  "Motion design": { Icon: Sparkles, color: "#9AA0A6" },
  "Design systems": { Icon: Component, color: "#9AA0A6" },
  Accessibility: { Icon: Accessibility, color: "#9AA0A6" },
};
